-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgixvBYHtGghcYzthshH146YKKO8otMpXFgKJ42G24fGSgCgYIKoZIzj0DAQehRANCAARdakZm/QoLeO+13Qk//9FVtWGbUvwcACHIUTeGKSaOpghFGokapeiJx/yFbyEMlzSN8m3SE5ymn7rEvwoAQBG7
-----END PRIVATE KEY-----