# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Hyphenate Messenger' do
    
    pod 'Hyphenate'
    pod 'Stripe'
    #pod 'Firebase/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire', '~> 4.4'
    pod 'SlimeRefresh'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Auth'
	pod 'Firebase/Storage'
    pod 'IHKeyboardAvoiding'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage'
    pod 'BRYXBanner'
end
