# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'Chat App For iOS 10' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat App For iOS 10
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'

end
