# Uncomment the next line to define a global platform for your project
    platform :ios, '10.0'

target 'Hyphenate-Demo-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hyphenate-Demo-Swift
    pod 'Hyphenate', '~> 3.3.1'
    pod 'MWPhotoBrowser', '~> 2.1.2'
    pod 'MJRefresh'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'Parse'
    pod 'Stripe'
    #pod 'Firebase/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire', '~> 4.4'
    pod 'SlimeRefresh'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'IHKeyboardAvoiding'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'SDWebImage'
    pod 'BRYXBanner'
end
